name: jhg_simulation
description: Pure dart jhg stuff
version: 2.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fast_immutable_collections: ^9.2.0
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.8.1
  quiver: ^3.2.1
  riverpod: ^2.4.9
  rxdart: ^0.27.7
  uuid: ^4.3.3
  async: ^2.11.0
  logging: ^1.2.0
  hive: ^2.2.3
  shelf_plus: ^1.7.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: 2.4.0
  firebase_dart: ^1.1.2
  memoized: ^2.2.1
  mocktail: ^1.0.3
  mockito: ^5.4.4
  universal_html: ^2.2.4
  dart_random_choice: ^0.2.0
  ml_linalg: ^13.12.2

  path: ^1.8.3
  csv: ^6.0.0
  string_similarity: ^2.1.1
  jhg_core: 
    git:
      url: git@github.com:JuniorHighGame/jhg2.git
      path: packages/core

dev_dependencies:
  build_runner: ^2.4.8
  expector: ^0.1.4
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  test: ^1.25.1
  spec: ^0.2.3
  all_lint_rules_community: ^0.0.40
  # custom_lint: ^0.0.9+1
  # jhg_linter:
  #   path: ../linter

  scidart_plot: ^0.0.2-dev.1
  scidart: ^0.0.2-dev.12
  scidart_io: ^0.0.2-dev.1
